#!/usr/bin/env bash
# Display listening TCP ports
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
netstat -tlnp | grep 'tcp' | awk '{print $1,$4,$5,$6}' | sed 's/:::/[::]/g' | sed 's/\([^:]\+\):\(.*\)/tcp \1/g' | sed 's/\(.*\):\(.*\)/\1 \2/g' | awk '{print $1,$2,$3,$4,$7}' | column -t

# Display listening UDP ports
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
netstat -ulnp | grep 'udp' | awk '{print $1,$4,"*:*",$6}' | sed 's/:::/[::]/g' | sed 's/\([^:]\+\):\(.*\)/udp \1/g' | sed 's/\(.*\):\(.*\)/\1 \2/g' | awk '{print $1,$2,$3,$4,$7}' | column -t
