#!/usr/bin/env bash

# Display the header
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Display the list of processes using the ps command with appropriate options
ps aux --forest
