#!/usr/bin/env bash
# This script displays the content of the current directory in a list format
for file in *; do

    if [ ! -h "$file" ] && [ ! -d "$file" ]; then
        # Extract the part of the name after the first dash
        name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name"
    fi
done
